//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsdfsd;


public class My234ComponentBasisJavaImplementation extends fsdfsd.My234ComponentAbstractJavaImplementation {
  public My234ComponentBasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

