//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package sdfsd;


public interface MyComponent2 extends de.tum.ascodt.repository.entities.Component {

  public static final String Implementation = "sdfsd.MyComponent2JavaImplementation";
  

}
 


