//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public class LB2NSNative2NativePlainPort extends LB2NSAbstractPort {
  private long _ref;
  public LB2NSNative2NativePlainPort() {
    super();
    createInstance();
  }
  /**
   * proxy for the native factory method
   */  
  public native void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native void destroyInstance(long ref);
  
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  @Override
  public void connect(LB2NS  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,_destination.getReference());
  }
  
  public native void connect(long ref,long cca_application);
   
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(LB2NS  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);
  }
  
  public long getReference(){
    return _ref;
  }
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void iterateBoundary() {
    //DO NOTHING HERE
  }
  
   public void iterateBoundaryParallel() {
    //DO NOTHING HERE
  }
  

  public void iterateInner() {
    //DO NOTHING HERE
  }
  
   public void iterateInnerParallel() {
    //DO NOTHING HERE
  }
  

  public void retrieveTimestep(double dt[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveTimestepParallel(double dt[]) {
    //DO NOTHING HERE
  }
  

  public void retrieveVelocitiesSize(int memoryX[],int memoryY[],int memoryZ[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveVelocitiesSizeParallel(int memoryX[],int memoryY[],int memoryZ[]) {
    //DO NOTHING HERE
  }
  

  public void retrieveVelocitiesCopy(double velocityX[],double velocityY[],double velocityZ[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveVelocitiesCopyParallel(double velocityX[],double velocityY[],double velocityZ[]) {
    //DO NOTHING HERE
  }
  
  

}
 


