//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public interface LB2NS  {
  class IntegerWrapper {
    public int value;
  }
  class DoubleWrapper {
    public double value;
  }
  class StringWrapper {
    public String value;
  }
  class BooleanWrapper {
    public boolean value;
  }
  public long getReference();
  public void setReference(long ref);
  //void lock();
 
  //void unlock();
  

  public void iterateBoundary();
  public void iterateBoundaryParallel();

  public void iterateInner();
  public void iterateInnerParallel();

  public void retrieveTimestep(double dt[]);
  public void retrieveTimestepParallel(double dt[]);

  public void retrieveVelocitiesSize(int memoryX[],int memoryY[],int memoryZ[]);
  public void retrieveVelocitiesSizeParallel(int memoryX[],int memoryY[],int memoryZ[]);

  public void retrieveVelocitiesCopy(double velocityX[],double velocityY[],double velocityZ[]);
  public void retrieveVelocitiesCopyParallel(double velocityX[],double velocityY[],double velocityZ[]);


}
 


