//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public class LBSolverDispatcher implements LBSolver {

  protected java.util.Set<LBSolver>  _destinations;
  
  public LBSolverDispatcher() {
    _destinations = java.util.Collections.synchronizedSet(new java.util.HashSet<LBSolver>());
  }
  
  public long getReference(){
    return 0;
  }
  
  
  public void setReference(long ref){
  }
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(LBSolver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "connect(...)", "port already was connected", null );
    }
    _destinations.add(port);
  }
    
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(LBSolver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port that was not connected before", null );
    }
     
    if (!_destinations.contains(port)) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port from port that was not connected before", null );
    }
    _destinations.remove(port);
  }
  
  public boolean isConnected(){
     return !_destinations.isEmpty();
  }
  
  public void setup(final String inputScenario) {
    for(LBSolver port: _destinations)
      port.setup(inputScenario);
  }
  
  public void setupParallel(final String inputScenario) {
    for(LBSolver port: _destinations)
      port.setupParallel(inputScenario);
  }
  
  public void setupForIntegerEnums(final String inputScenario) {
    for(LBSolver port: _destinations){
      
      port.setup(inputScenario);
      
    }
  }
  public void setupCommForNSRegion(final int startOfRegion[],final int endOfRegion[],final String commids[]) {
    for(LBSolver port: _destinations)
      port.setupCommForNSRegion(startOfRegion,endOfRegion,commids);
  }
  
  public void setupCommForNSRegionParallel(final int startOfRegion[],final int endOfRegion[],final String commids[]) {
    for(LBSolver port: _destinations)
      port.setupCommForNSRegionParallel(startOfRegion,endOfRegion,commids);
  }
  
  public void setupCommForNSRegionForIntegerEnums(final int startOfRegion[],final int endOfRegion[],final String commids[]) {
    for(LBSolver port: _destinations){
      
      port.setupCommForNSRegion(startOfRegion,endOfRegion,commids);
      
    }
  }
  public void solve() {
    for(LBSolver port: _destinations)
      port.solve();
  }
  
  public void solveParallel() {
    for(LBSolver port: _destinations)
      port.solveParallel();
  }
  
  public void solveForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.solve();
      
    }
  }
  public void solveOneTimestep() {
    for(LBSolver port: _destinations)
      port.solveOneTimestep();
  }
  
  public void solveOneTimestepParallel() {
    for(LBSolver port: _destinations)
      port.solveOneTimestepParallel();
  }
  
  public void solveOneTimestepForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.solveOneTimestep();
      
    }
  }
  public void setVelocities(final double velocitiesX[],final double velocitiesY[],final double velocitiesZ[]) {
    for(LBSolver port: _destinations)
      port.setVelocities(velocitiesX,velocitiesY,velocitiesZ);
  }
  
  public void setVelocitiesParallel(final double velocitiesX[],final double velocitiesY[],final double velocitiesZ[]) {
    for(LBSolver port: _destinations)
      port.setVelocitiesParallel(velocitiesX,velocitiesY,velocitiesZ);
  }
  
  public void setVelocitiesForIntegerEnums(final double velocitiesX[],final double velocitiesY[],final double velocitiesZ[]) {
    for(LBSolver port: _destinations){
      
      port.setVelocities(velocitiesX,velocitiesY,velocitiesZ);
      
    }
  }
  public void setPressure(final double pressure[]) {
    for(LBSolver port: _destinations)
      port.setPressure(pressure);
  }
  
  public void setPressureParallel(final double pressure[]) {
    for(LBSolver port: _destinations)
      port.setPressureParallel(pressure);
  }
  
  public void setPressureForIntegerEnums(final double pressure[]) {
    for(LBSolver port: _destinations){
      
      port.setPressure(pressure);
      
    }
  }
  public void setGradients(final double gradients[]) {
    for(LBSolver port: _destinations)
      port.setGradients(gradients);
  }
  
  public void setGradientsParallel(final double gradients[]) {
    for(LBSolver port: _destinations)
      port.setGradientsParallel(gradients);
  }
  
  public void setGradientsForIntegerEnums(final double gradients[]) {
    for(LBSolver port: _destinations){
      
      port.setGradients(gradients);
      
    }
  }
  public void closeLBProfiles() {
    for(LBSolver port: _destinations)
      port.closeLBProfiles();
  }
  
  public void closeLBProfilesParallel() {
    for(LBSolver port: _destinations)
      port.closeLBProfilesParallel();
  }
  
  public void closeLBProfilesForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.closeLBProfiles();
      
    }
  }
  public void printLBDensity() {
    for(LBSolver port: _destinations)
      port.printLBDensity();
  }
  
  public void printLBDensityParallel() {
    for(LBSolver port: _destinations)
      port.printLBDensityParallel();
  }
  
  public void printLBDensityForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.printLBDensity();
      
    }
  }
  public void printLBProfiles() {
    for(LBSolver port: _destinations)
      port.printLBProfiles();
  }
  
  public void printLBProfilesParallel() {
    for(LBSolver port: _destinations)
      port.printLBProfilesParallel();
  }
  
  public void printLBProfilesForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.printLBProfiles();
      
    }
  }
  public void forwardVelocities(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations)
      port.forwardVelocities(keys,offsets,flips,values,ackn);
  }
  
  public void forwardVelocitiesParallel(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations)
      port.forwardVelocitiesParallel(keys,offsets,flips,values,ackn);
  }
  
  public void forwardVelocitiesForIntegerEnums(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations){
      
      port.forwardVelocities(keys,offsets,flips,values,ackn);
      
    }
  }
  public void forwardPressure(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations)
      port.forwardPressure(keys,offsets,flips,values,ackn);
  }
  
  public void forwardPressureParallel(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations)
      port.forwardPressureParallel(keys,offsets,flips,values,ackn);
  }
  
  public void forwardPressureForIntegerEnums(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    for(LBSolver port: _destinations){
      
      port.forwardPressure(keys,offsets,flips,values,ackn);
      
    }
  }
  public void syncr(int value[]) {
    for(LBSolver port: _destinations)
      port.syncr(value);
  }
  
  public void syncrParallel(int value[]) {
    for(LBSolver port: _destinations)
      port.syncrParallel(value);
  }
  
  public void syncrForIntegerEnums(int value[]) {
    for(LBSolver port: _destinations){
      
      port.syncr(value);
      
    }
  }
  public void plot() {
    for(LBSolver port: _destinations)
      port.plot();
  }
  
  public void plotParallel() {
    for(LBSolver port: _destinations)
      port.plotParallel();
  }
  
  public void plotForIntegerEnums() {
    for(LBSolver port: _destinations){
      
      port.plot();
      
    }
  }
  
//  public void lock() {
//    if (_destination!=null) {
//      _destination.lock();
//    }
//  }
 
//  public void unlock() {
//    if (_destination!=null) {
//      _destination.unlock();
//    }
//  }
  
}
 


