//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public class NS2LBNative2NativePlainPort extends NS2LBAbstractPort {
  private long _ref;
  public NS2LBNative2NativePlainPort() {
    super();
    createInstance();
  }
  /**
   * proxy for the native factory method
   */  
  public native void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native void destroyInstance(long ref);
  
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  @Override
  public void connect(NS2LB  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,_destination.getReference());
  }
  
  public native void connect(long ref,long cca_application);
   
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(NS2LB  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);
  }
  
  public long getReference(){
    return _ref;
  }
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void iterate() {
    //DO NOTHING HERE
  }
  
   public void iterateParallel() {
    //DO NOTHING HERE
  }
  

  public void retrieveTimestep(double timestep[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveTimestepParallel(double timestep[]) {
    //DO NOTHING HERE
  }
  

  public void retrieveVelocitiesSize(int memory[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveVelocitiesSizeParallel(int memory[]) {
    //DO NOTHING HERE
  }
  

  public void retrieveVelocitiesCopy(double velocityX[],double velocityY[],double velocityZ[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveVelocitiesCopyParallel(double velocityX[],double velocityY[],double velocityZ[]) {
    //DO NOTHING HERE
  }
  

  public void retrieveJacobianCopy(double jacobian[]) {
    //DO NOTHING HERE
  }
  
   public void retrieveJacobianCopyParallel(double jacobian[]) {
    //DO NOTHING HERE
  }
  

  public void retrievePressureCopy(double pressure[]) {
    //DO NOTHING HERE
  }
  
   public void retrievePressureCopyParallel(double pressure[]) {
    //DO NOTHING HERE
  }
  
  

}
 


