//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public abstract class NSAbstractJavaImplementation extends SocketComponent implements NS{
  protected de.tum.ascodt.plugin.ui.tabs.SocketClientAppsTab _appTab;
  protected String   _instanceName;
  protected String _projectLocation;
  public NSAbstractJavaImplementation( String instanceName ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    _instanceName = instanceName;
    _appTab = new de.tum.ascodt.plugin.ui.tabs.SocketClientAppsTab("cca.cfd.NS",this, de.tum.ascodt.plugin.ui.views.AppsViewContainer.ID);
    _appTab.setVisible(true);
    _appTab.addListener(this);
    
    
  }
  
  public de.tum.ascodt.repository.Target getTarget() {
     return de.tum.ascodt.repository.Target.createCxxRemoteSocketTarget();
  }
  
  public de.tum.ascodt.repository.TargetParameters getTargetParameters(){
     return de.tum.ascodt.repository.TargetParameters.createRemoteSocketParameters(
          _appTab.getHost(),
          _appTab.getPort()
          );
  }

  public long getReference(){
    return 0;
  }  
  
  public void setReference(long ref){
   
  }
  
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void lock() {
    
  }

  public void setProjectLocation(String location){
     _projectLocation = location;
     _appTab.setProjectLocation(location);
     if(_appTab.hasApplicationSettings())
          _appTab.execute();
  }
 
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void unlock() {
    
  }
  
 
  public void destroy()  {
          try{
               if(isConnected())
                    sendIntData(1);
          }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
               de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
          }
          super.close();
          _appTab.removeListener(this);
          _appTab.setVisible(false);
          _appTab.dispose();
    
  }
  
  public boolean isValid() {
     return true;
  }


  public boolean hasGUI() {
    // @todo Insert your code here
    return false;
  }
  
  
  public void openGUI() {
    // @todo Insert your code here
  }
  
  
  public void closeGUI() {
    // @todo Insert your code here
  }
  
  @Override
  public String getInstanceName() {
    return _instanceName;
  }

  @Override
  public void setInstanceName(String instanceName) {
    _instanceName=instanceName;
  }
  
  public void createInstance(){
     
  }
 
  public void destroyInstance(){
  }
 
  

  public void setup(final String inputScenario) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=69;
         sendIntData(methodId);
         sendStringData(inputScenario);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void setupParallel(final String inputScenario) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=69+1;
         sendIntData(methodId);
         sendStringData(inputScenario);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void setupCommForLBRegion(final int startOfRegion[],final int endOfRegion[],final String commids[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=71;
         sendIntData(methodId);
         sendIntData(startOfRegion.length);
sendIntData(startOfRegion);
sendIntData(endOfRegion.length);
sendIntData(endOfRegion);
sendIntData(commids.length);
sendStringData(commids);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void setupCommForLBRegionParallel(final int startOfRegion[],final int endOfRegion[],final String commids[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=71+1;
         sendIntData(methodId);
         sendIntData(startOfRegion.length);
sendIntData(startOfRegion);
sendIntData(endOfRegion.length);
sendIntData(endOfRegion);
sendIntData(commids.length);
sendStringData(commids);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void solve() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=73;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void solveParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=73+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void solveOneTimestepPhaseOne() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=75;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void solveOneTimestepPhaseOneParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=75+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void solveOneTimestepPhaseTwo() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=77;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void solveOneTimestepPhaseTwoParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=77+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void setVelocities(final double velocitiesX[],final double velocitiesY[],final double velocitiesZ[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=79;
         sendIntData(methodId);
         sendIntData(velocitiesX.length);
sendDoubleData(velocitiesX);
sendIntData(velocitiesY.length);
sendDoubleData(velocitiesY);
sendIntData(velocitiesZ.length);
sendDoubleData(velocitiesZ);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void setVelocitiesParallel(final double velocitiesX[],final double velocitiesY[],final double velocitiesZ[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=79+1;
         sendIntData(methodId);
         sendIntData(velocitiesX.length);
sendDoubleData(velocitiesX);
sendIntData(velocitiesY.length);
sendDoubleData(velocitiesY);
sendIntData(velocitiesZ.length);
sendDoubleData(velocitiesZ);

           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void printNSPressure() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=81;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void printNSPressureParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=81+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void printNSProfiles() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=83;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void printNSProfilesParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=83+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void closeNSProfiles() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=85;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void closeNSProfilesParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=85+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void iterateBoundary() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=87;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void iterateBoundaryParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=87+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void iterateInner() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=89;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void iterateInnerParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=89+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void forwardVelocities(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=91;
         sendIntData(methodId);
         sendIntData(keys.length);
sendIntData(keys);
sendIntData(offsets.length);
sendIntData(offsets);
sendIntData(flips.length);
sendIntData(flips);
sendIntData(values.length);
sendDoubleData(values);
sendIntData(ackn);

         readIntData(ackn,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void forwardVelocitiesParallel(int keys[],int offsets[],int flips[],double values[],int ackn[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=91+1;
         sendIntData(methodId);
         sendIntData(keys.length);
sendIntData(keys);
sendIntData(offsets.length);
sendIntData(offsets);
sendIntData(flips.length);
sendIntData(flips);
sendIntData(values.length);
sendDoubleData(values);
sendIntData(ackn);

         readIntData(ackn,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void plot() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=93;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void plotParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=93+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void syncr(int value[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=95;
         sendIntData(methodId);
         sendIntData(value);

         readIntData(value,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void syncrParallel(int value[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=95+1;
         sendIntData(methodId);
         sendIntData(value);

         readIntData(value,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void iterate() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=54;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void iterateParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=54+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void retrieveTimestep(double timestep[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=56;
         sendIntData(methodId);
         sendDoubleData(timestep);

         readDoubleData(timestep,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void retrieveTimestepParallel(double timestep[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=56+1;
         sendIntData(methodId);
         sendDoubleData(timestep);

         readDoubleData(timestep,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void retrieveVelocitiesSize(int memory[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=58;
         sendIntData(methodId);
         sendIntData(memory);

         readIntData(memory,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void retrieveVelocitiesSizeParallel(int memory[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=58+1;
         sendIntData(methodId);
         sendIntData(memory);

         readIntData(memory,1);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void retrieveVelocitiesCopy(double velocityX[],double velocityY[],double velocityZ[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=60;
         sendIntData(methodId);
         sendIntData(velocityX.length);
sendDoubleData(velocityX);
sendIntData(velocityY.length);
sendDoubleData(velocityY);
sendIntData(velocityZ.length);
sendDoubleData(velocityZ);

         int velocityX_len;
velocityX_len=readIntData();
readDoubleData(velocityX,velocityX_len);
int velocityY_len;
velocityY_len=readIntData();
readDoubleData(velocityY,velocityY_len);
int velocityZ_len;
velocityZ_len=readIntData();
readDoubleData(velocityZ,velocityZ_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void retrieveVelocitiesCopyParallel(double velocityX[],double velocityY[],double velocityZ[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=60+1;
         sendIntData(methodId);
         sendIntData(velocityX.length);
sendDoubleData(velocityX);
sendIntData(velocityY.length);
sendDoubleData(velocityY);
sendIntData(velocityZ.length);
sendDoubleData(velocityZ);

         int velocityX_len;
velocityX_len=readIntData();
readDoubleData(velocityX,velocityX_len);
int velocityY_len;
velocityY_len=readIntData();
readDoubleData(velocityY,velocityY_len);
int velocityZ_len;
velocityZ_len=readIntData();
readDoubleData(velocityZ,velocityZ_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void retrieveJacobianCopy(double jacobian[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=62;
         sendIntData(methodId);
         sendIntData(jacobian.length);
sendDoubleData(jacobian);

         int jacobian_len;
jacobian_len=readIntData();
readDoubleData(jacobian,jacobian_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void retrieveJacobianCopyParallel(double jacobian[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=62+1;
         sendIntData(methodId);
         sendIntData(jacobian.length);
sendDoubleData(jacobian);

         int jacobian_len;
jacobian_len=readIntData();
readDoubleData(jacobian,jacobian_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  public void retrievePressureCopy(double pressure[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=64;
         sendIntData(methodId);
         sendIntData(pressure.length);
sendDoubleData(pressure);

         int pressure_len;
pressure_len=readIntData();
readDoubleData(pressure,pressure_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void retrievePressureCopyParallel(double pressure[]) {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=64+1;
         sendIntData(methodId);
         sendIntData(pressure.length);
sendDoubleData(pressure);

         int pressure_len;
pressure_len=readIntData();
readDoubleData(pressure,pressure_len);
  
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  /**
   * Uses port
   */
  protected cca.cfd.LBSolverSocketDispatcher _lb = null;
  
  
 
  
  
  /**
   * @see Case class 
   */
  public cca.cfd.LBSolver createPortForlb(
     de.tum.ascodt.repository.Target target,
     de.tum.ascodt.repository.TargetParameters targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    
    cca.cfd.LBSolverSocketPort result = null;
    if (
      target.getType()==de.tum.ascodt.repository.Target.TargetType.JavaLocal||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.JavaNative||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.FortranNative
    ) {
      result = new cca.cfd.LBSolverSocket2JavaPlainPort();
     
    }else if(
      target.getType()==de.tum.ascodt.repository.Target.TargetType.FortranRemoteSocket||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.CxxRemoteSocket
    ){
          result = new cca.cfd.LBSolverSocket2SocketPlainPort(
               targetParameters.getStringParameter("host"),
               targetParameters.getIntParameter("port")
          );
    }
    assert(result!=null);
    _appTab.addListener(result);
    long port_ref=createClientPortForlb(result);
    result.setReference(port_ref); 
    
    
    
    
    
    return result;
  }
  
  

   long createClientPortForlb(cca.cfd.LBSolverSocketPort socketPort) throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int method=20;
     long ref=-1;
     sendIntData(method);
     sendStringData(socketPort.getHost());
     sendIntData(socketPort.getPort());
     socketPort.open();
     de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println("Create");
     ref=readLongData();
     de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println("Created: " + ref);
     return ref;
  }
  
  /**
   * @see Case class 
   */
  public void connectlb(final cca.cfd.LBSolver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    //assert(_isLocked);
    assert(port!=null);
     if(_lb==null){
       
        _lb = new cca.cfd.LBSolverSocketDispatcher();
        _appTab.addListener(_lb);
        long dispRef = connectClientDispatcherlb(_lb.getHost(),_lb.getPort());
        _lb.setReference(dispRef);
     }
     _lb.connect(port);
              
   
   
  }
  
  public long  connectClientDispatcherlb(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int method=21;
     long ref=-1;
     sendIntData(method);
     sendStringData(host);
     sendIntData(port);
     _lb.open();
     ref=readLongData();
     de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println("Connected: " + ref);
     return ref;
  }
  
  
  
  /**
   * @see Case class 
   */
  public void disconnectlb(final cca.cfd.LBSolver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    assert(port!=null);
    if(_lb!=null&&_lb.isConnected()){
               assert(_lb!=null );
               _appTab.removeListener(( cca.cfd.LBSolverSocketPort)port);
               _lb.disconnect(port);
               if(!_lb.isConnected()){
                 _appTab.removeListener(_lb);
                 disconnectDispatcherlb();
                 _lb.close();
                 _lb = null;
               }
    }
  }
  
  public void disconnectDispatcherlb() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=22;
     sendIntData(methodId);
     
  }
  
  


}
 


