#ifndef DE_TUM_TEST_TESTIMPLEMENTATION_H_
#define DE_TUM_TEST_TESTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "de/tum/test/TestAbstractImplementation.h"
#include <string>
namespace de { 
namespace tum { 
  namespace test { 
    
     class TestImplementation;
} 
} 
}  

class de::tum::test::TestImplementation : public de::tum::test::TestAbstractImplementation{
     public:
          TestImplementation();
          ~TestImplementation();
};     


#endif
