//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsdfsd;


public interface My234Component extends de.tum.ascodt.repository.entities.Component {

  public static final String Implementation = "fsdfsd.My234ComponentJavaImplementation";
  

}
 


