//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class LaplaceBasisJavaImplementation extends examples.heat.LaplaceAbstractJavaImplementation {
	
	public LaplaceBasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
		super(identifier);
	}

	@Override
	public void getStencil(double[] stencil) {
		stencil[0]=1;
		stencil[1]=1;
		stencil[2]=-4;
		stencil[3]=1;
		stencil[4]=1;
	}

	/**
	 * Provides methods block
	 */

}


