//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class LinePlotterBasisJavaImplementation extends examples.heat.LinePlotterAbstractJavaImplementation {
  public LinePlotterBasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }

@Override
public void plotPoint(String name, double x, double y) {
	// TODO Auto-generated method stub
	
}
  
  /**
   * Provides methods block
   */

}
 

