#ifndef EXAMPLES_HEAT_MESHIMPLEMENTATION_H_
#define EXAMPLES_HEAT_MESHIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/heat/MeshAbstractImplementation.h"
#include <string>
namespace examples { 
namespace heat { 
  
     class MeshImplementation;
} 
}

class examples::heat::MeshImplementation : public examples::heat::MeshAbstractImplementation{
private:
	int _dims[2];
	double* _data;
public:
          MeshImplementation();
          ~MeshImplementation();
          void allocate(const int* dim, const int dim_len);
          void copyData(double* data, const int data_len);
          void getData(void*& handle);
};     


#endif
