#ifndef TEST_AABSTRACTIMPLEMENTATION_H_
#define TEST_AABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "test/FooNativeDispatcher.h"

#include "test/Foo.h"

#include "Component.h"
namespace test { 

     class AAbstractImplementation;
}



class test::AAbstractImplementation: public Component ,public test::Foo{
     protected:
       test::FooNativeDispatcher* _foo;
   
     public:
       AAbstractImplementation();
       virtual ~AAbstractImplementation();
       /**
        * @see Case class 
        */
       void connectfoo(test::FooNativeDispatcher* port);
       void disconnectfoo();
 
};     


#endif
