#ifndef TEST_FOO_H_
#define TEST_FOO_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace test { 

     class Foo;
}

class test::Foo {
  public:
    virtual ~Foo(){}
     virtual void bar()=0;


};

#endif
