//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package test;


public class FooPlainJavaPort extends FooAbstractPort {

  public FooPlainJavaPort() {
    super();
  }
  

  public void bar() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.bar();
      //_destination.unlock();
    //}
  }
  
  

}
 


