//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples;


public abstract class AAbstractJavaImplementation extends SocketComponent implements A{
  protected de.tum.ascodt.plugin.ui.tabs.SocketClientAppsTab _appTab;
  protected String   _instanceName;
  protected String _projectLocation;
  public AAbstractJavaImplementation( String instanceName ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    _instanceName = instanceName;
    _appTab = new de.tum.ascodt.plugin.ui.tabs.SocketClientAppsTab("examples.A",this, de.tum.ascodt.plugin.ui.views.AppsViewContainer.ID);
    _appTab.setVisible(true);
    _appTab.addListener(this);
    
    
  }
  
  public de.tum.ascodt.repository.Target getTarget() {
     return de.tum.ascodt.repository.Target.createCxxRemoteSocketTarget();
  }
  
  public de.tum.ascodt.repository.TargetParameters getTargetParameters(){
     return de.tum.ascodt.repository.TargetParameters.createRemoteSocketParameters(
          _appTab.getHost(),
          _appTab.getPort()
          );
  }

  public long getReference(){
    return 0;
  }  
  
  public void setReference(long ref){
   
  }
  
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void lock() {
    
  }

  public void setProjectLocation(String location){
     _projectLocation = location;
     _appTab.setProjectLocation(location);
     if(_appTab.hasApplicationSettings())
          _appTab.execute();
  }
 
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void unlock() {
    
  }
  
 
  public void destroy()  {
          try{
               if(isConnected())
                    sendIntData(1);
          }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
               de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
          }
          super.close();
          _appTab.removeListener(this);
          _appTab.setVisible(false);
          _appTab.dispose();
    
  }
  
  public boolean isValid() {
     return true;
  }


  public boolean hasGUI() {
    // @todo Insert your code here
    return false;
  }
  
  
  public void openGUI() {
    // @todo Insert your code here
  }
  
  
  public void closeGUI() {
    // @todo Insert your code here
  }
  
  @Override
  public String getInstanceName() {
    return _instanceName;
  }

  @Override
  public void setInstanceName(String instanceName) {
    _instanceName=instanceName;
  }
  
  public void createInstance(){
     
  }
 
  public void destroyInstance(){
  }
 
  

  public void go() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=5;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }

  public void goParallel() {
    //__SWITCH_SYNC_ASYNC__
    try{
         int methodId=5+1;
         sendIntData(methodId);
         
           
    }catch(de.tum.ascodt.utils.exceptions.ASCoDTException e){
       de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
    }  
  }
    

  /**
   * Uses port
   */
  protected examples.FooSocketDispatcher _fooHandler = null;
  
  
 
  
  
  /**
   * @see Case class 
   */
  public examples.Foo createPortForfooHandler(
     de.tum.ascodt.repository.Target target,
     de.tum.ascodt.repository.TargetParameters targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    
    examples.FooSocketPort result = null;
    if (
      target.getType()==de.tum.ascodt.repository.Target.TargetType.JavaLocal||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.JavaNative||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.FortranNative
    ) {
      result = new examples.FooSocket2JavaPlainPort();
     
    }else if(
      target.getType()==de.tum.ascodt.repository.Target.TargetType.FortranRemoteSocket||
      target.getType()==de.tum.ascodt.repository.Target.TargetType.CxxRemoteSocket
    ){
          result = new examples.FooSocket2SocketPlainPort(
               targetParameters.getStringParameter("host"),
               targetParameters.getIntParameter("port")
          );
    }
    assert(result!=null);
    _appTab.addListener(result);
    long port_ref=createClientPortForfooHandler(result);
    result.setReference(port_ref); 
    
    
    
    
    
    return result;
  }
  
  

   long createClientPortForfooHandler(examples.FooSocketPort socketPort) throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int method=7;
     long ref=-1;
     sendIntData(method);
     sendStringData(socketPort.getHost());
     sendIntData(socketPort.getPort());
     socketPort.open();
     ref=readLongData();
     return ref;
  }
  
  /**
   * @see Case class 
   */
  public void connectfooHandler(final examples.Foo  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    //assert(_isLocked);
    assert(port!=null);
     if(_fooHandler==null){
       
        _fooHandler = new examples.FooSocketDispatcher();
        _appTab.addListener(_fooHandler);
        long dispRef = connectClientDispatcherfooHandler(_fooHandler.getHost(),_fooHandler.getPort());
        _fooHandler.setReference(dispRef);
     }
     _fooHandler.connect(port);
              
   
   
  }
  
  public long  connectClientDispatcherfooHandler(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int method=8;
     long ref=-1;
     sendIntData(method);
     sendStringData(host);
     sendIntData(port);
     _fooHandler.open();
     ref=readLongData();
     
     return ref;
  }
  
  
  
  /**
   * @see Case class 
   */
  public void disconnectfooHandler(final examples.Foo  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    assert(port!=null);
    if(_fooHandler!=null&&_fooHandler.isConnected()){
               assert(_fooHandler!=null );
               _appTab.removeListener(( examples.FooSocketPort)port);
               _fooHandler.disconnect(port);
               if(!_fooHandler.isConnected()){
                 _appTab.removeListener(_fooHandler);
                 disconnectDispatcherfooHandler();
                 _fooHandler.close();
                 _fooHandler = null;
               }
    }
  }
  
  public void disconnectDispatcherfooHandler() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=9;
     sendIntData(methodId);
     
  }
  
  


}
 


