#ifndef EXAMPLES_AABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_AABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "examples/FooNativeDispatcher.h"

#include "examples/Driver.h"

#include "Component.h"
namespace examples { 

     class AAbstractImplementation;
}



class examples::AAbstractImplementation: public Component ,public examples::Driver{
     protected:
       examples::FooNativeDispatcher* _fooHandler;
   
     public:
       AAbstractImplementation();
       virtual ~AAbstractImplementation();
       /**
        * @see Case class 
        */
       void connectfooHandler(examples::FooNativeDispatcher* port);
       void disconnectfooHandler();
 
		void goParallel();
};     


#endif
