#ifndef EXAMPLES_BABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_BABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/Foo.h"

#include "Component.h"
namespace examples { 

     class BAbstractImplementation;
}



class examples::BAbstractImplementation: public Component ,public examples::Foo{
     protected:
          
     public:
       BAbstractImplementation();
       virtual ~BAbstractImplementation();
		void barParallel(const int a,const int b);
};     


#endif
