#ifndef EXAMPLES_FOO_H_
#define EXAMPLES_FOO_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace examples { 

     class Foo;
}

class examples::Foo {
  public:
    virtual ~Foo(){}
     virtual void bar(const int a,const int b)=0;
     virtual void barParallel(const int a,const int b)=0;


};

#endif
