//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples;


public class FooPlainJavaPort extends FooAbstractPort {

  public FooPlainJavaPort() {
    super();
  }
  

  public void bar(final int a,final int b) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.bar(a,b);
      //_destination.unlock();
    //}
  }
  
  public void barParallel(final int a,final int b) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.barParallel(a,b);
      //_destination.unlock();
    //}
  }
  
  
  
  

}
 


