#ifndef EXAMPLES_BIMPLEMENTATION_H_
#define EXAMPLES_BIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/BAbstractImplementation.h"
#include <string>
namespace examples { 

     class BImplementation;
}

class examples::BImplementation : public examples::BAbstractImplementation{
     public:
          BImplementation();
          ~BImplementation();
          void bar(const int a,const int b);
};     


#endif
