#ifndef CCA_CFD_DRIVER_H_
#define CCA_CFD_DRIVER_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace cca { 
namespace cfd { 
  
     class Driver;
} 
}

class cca::cfd::Driver {
  public:
    virtual ~Driver(){}
     virtual void go(const std::string configFile)=0;
     virtual void goParallel(const std::string configFile)=0;


};

#endif
