#ifndef CCA_CFD_LB2NS2NATIVE2JAVAPLAINPORT_H_
#define CCA_CFD_LB2NS2NATIVE2JAVAPLAINPORT_H_ 

#include "cca/cfd/LB2NS.h"

#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#ifdef JAVA
#include <jni.h> 
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_cca_cfd_LB2NSNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_cca_cfd_LB2NSNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace cca { 
namespace cfd { 
  
     class LB2NSNative2JavaPlainPort;
} 
}

class cca::cfd::LB2NSNative2JavaPlainPort: public cca::cfd::LB2NS{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    LB2NSNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~LB2NSNative2JavaPlainPort();
    void iterateBoundary();  
    void iterateBoundaryParallel();
   
    void iterateInner();  
    void iterateInnerParallel();
   
    void retrieveTimestep(double& dt);  
    void retrieveTimestepParallel(double& dt);
   
    void retrieveVelocitiesSize(int& memoryX,int& memoryY,int& memoryZ);  
    void retrieveVelocitiesSizeParallel(int& memoryX,int& memoryY,int& memoryZ);
   
    void retrieveVelocitiesCopy(double* velocityX, const int velocityX_len,double* velocityY, const int velocityY_len,double* velocityZ, const int velocityZ_len);  
    void retrieveVelocitiesCopyParallel(double* velocityX, const int velocityX_len,double* velocityY, const int velocityY_len,double* velocityZ, const int velocityZ_len);
   
};
#endif
#endif
