//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package test;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Label;

public class MyVTKComponentUI extends de.tum.ascodt.plugin.ui.tabs.UITab {
     
     public MyVTKComponentUI(MyVTKComponent component){
          super(component);
     }
     /**
      * here you need to instantiate your own controls
      * use _tabFolderPage as parent
      */
     @Override
     protected void createControlGroup() {
          // TODO Auto-generated method stub
    	 this.tabFolderPage.setLayout(new FillLayout());
          Label hello = new Label(this.tabFolderPage,SWT.None);
          hello.setText("Hello World");
     }
     
     private MyVTKComponent getCastedComponent(){
          if(_component instanceof MyVTKComponent){
               return (MyVTKComponent) _component;
          }
          return null;
     }
}
