#ifndef EXAMPLES_HEAT_ADAMSMOULTONABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_HEAT_ADAMSMOULTONABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "examples/heat/SolverNativeDispatcher.h"

#include "examples/heat/Integrator.h"

namespace examples { 
namespace heat { 
  
     class AdamsMoultonAbstractImplementation;
} 
}



class examples::heat::AdamsMoultonAbstractImplementation : public examples::heat::Integrator{
     protected:
       examples::heat::SolverNativeDispatcher* _solver;
   
     public:
       AdamsMoultonAbstractImplementation();
       virtual ~AdamsMoultonAbstractImplementation();
       /**
        * @see Case class 
        */
       void connectsolver(examples::heat::SolverNativeDispatcher* port);
       void disconnectsolver();
 
};     


#endif
