//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public interface AppDriver extends de.tum.Driver,de.tum.ascodt.repository.entities.Component {

  public static final String Implementation = "examples.heat.AppDriverJavaImplementation";
  

  /**
   * Connect a uses port.
   *
   * @throws ASCoDTException If you connect the same object twice and if you 
   *           try to connect to several ports even though 
   *           mayConnectMultiplePortsTostencil() returns false.
   * @param port Valid port instance. Use factory method createPortForstencil() to 
   *           create port instances. 
   */
  void connectstencil(examples.heat.Stencil  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Create a port object for a given target. Each class is well aware of its 
   * own target and thus can create the port that is best suited for it. If 
   * the target is running remotely, e.g., and the destination target it the 
   * same remote machine, both components can communicate directly and the 
   * returned java port simply is a representant for this direct communication.
   */
  examples.heat.Stencil createPortForstencil(
     de.tum.ascodt.repository.Target  target,
     de.tum.ascodt.repository.TargetParameters  targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Disconnect a port.
   * 
   * @throws ASCoDTException If the port has not been successfully connected to 
   *            the component before. 
   */
  void disconnectstencil(examples.heat.Stencil  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  //boolean mayConnectMultiplePortsTostencil();

  /**
   * Connect a uses port.
   *
   * @throws ASCoDTException If you connect the same object twice and if you 
   *           try to connect to several ports even though 
   *           mayConnectMultiplePortsTointegrator() returns false.
   * @param port Valid port instance. Use factory method createPortForintegrator() to 
   *           create port instances. 
   */
  void connectintegrator(examples.heat.Integrator  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Create a port object for a given target. Each class is well aware of its 
   * own target and thus can create the port that is best suited for it. If 
   * the target is running remotely, e.g., and the destination target it the 
   * same remote machine, both components can communicate directly and the 
   * returned java port simply is a representant for this direct communication.
   */
  examples.heat.Integrator createPortForintegrator(
     de.tum.ascodt.repository.Target  target,
     de.tum.ascodt.repository.TargetParameters  targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Disconnect a port.
   * 
   * @throws ASCoDTException If the port has not been successfully connected to 
   *            the component before. 
   */
  void disconnectintegrator(examples.heat.Integrator  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  //boolean mayConnectMultiplePortsTointegrator();

  /**
   * Connect a uses port.
   *
   * @throws ASCoDTException If you connect the same object twice and if you 
   *           try to connect to several ports even though 
   *           mayConnectMultiplePortsTomesh() returns false.
   * @param port Valid port instance. Use factory method createPortFormesh() to 
   *           create port instances. 
   */
  void connectmesh(examples.heat.fMesh  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Create a port object for a given target. Each class is well aware of its 
   * own target and thus can create the port that is best suited for it. If 
   * the target is running remotely, e.g., and the destination target it the 
   * same remote machine, both components can communicate directly and the 
   * returned java port simply is a representant for this direct communication.
   */
  examples.heat.fMesh createPortFormesh(
     de.tum.ascodt.repository.Target  target,
     de.tum.ascodt.repository.TargetParameters  targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Disconnect a port.
   * 
   * @throws ASCoDTException If the port has not been successfully connected to 
   *            the component before. 
   */
  void disconnectmesh(examples.heat.fMesh  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  //boolean mayConnectMultiplePortsTomesh();

  /**
   * Connect a uses port.
   *
   * @throws ASCoDTException If you connect the same object twice and if you 
   *           try to connect to several ports even though 
   *           mayConnectMultiplePortsTovis() returns false.
   * @param port Valid port instance. Use factory method createPortForvis() to 
   *           create port instances. 
   */
  void connectvis(examples.heat.RegularGrid  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Create a port object for a given target. Each class is well aware of its 
   * own target and thus can create the port that is best suited for it. If 
   * the target is running remotely, e.g., and the destination target it the 
   * same remote machine, both components can communicate directly and the 
   * returned java port simply is a representant for this direct communication.
   */
  examples.heat.RegularGrid createPortForvis(
     de.tum.ascodt.repository.Target  target,
     de.tum.ascodt.repository.TargetParameters  targetParameters
  ) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  /**
   * Disconnect a port.
   * 
   * @throws ASCoDTException If the port has not been successfully connected to 
   *            the component before. 
   */
  void disconnectvis(examples.heat.RegularGrid  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  
  //boolean mayConnectMultiplePortsTovis();

}
 


