!
! ASCoDT - Advanced Scientific Computing Development Toolkit
!
! This file was generated by ASCoDT's simplified SIDL compiler.
!
! Authors: Tobias Weinzierl, Atanas Atanasov   
!
module examples_heat_FGausSeidelAbstractImplementation

implicit none

type, public :: FGausSeidelAbstractImplementation 
     ! Declaration of private members
      
     !list of procedures
     contains
     
     procedure,public::is_valid
     !__PROVIDE_PORTS__
end type FGausSeidelAbstractImplementation

contains 

logical function is_valid(this)
    class(FGausSeidelAbstractImplementation) :: this
    is_valid = .True.
end function is_valid

end module  examples_heat_FGausSeidelAbstractImplementation
