//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class fMeshNative2NativePlainPort extends fMeshAbstractPort {
  private long _ref;
  public fMeshNative2NativePlainPort() {
    super();
    createInstance();
  }
  /**
   * proxy for the native factory method
   */  
  public native void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native void destroyInstance(long ref);
  
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  @Override
  public void connect(fMesh  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,_destination.getReference());
  }
  
  public native void connect(long ref,long cca_application);
   
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(fMesh  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);
  }
  
  public long getReference(){
    return _ref;
  }
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void allocate(final int dim[]) {
    //DO NOTHING HERE
  }
  

  public void copyData(double data[]) {
    //DO NOTHING HERE
  }
  

  public void getData(long handle[]) {
    //DO NOTHING HERE
  }
  
  

}
 


