//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class fMeshPlainJavaPort extends fMeshAbstractPort {

  public fMeshPlainJavaPort() {
    super();
  }
  

  public void allocate(final int dim[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.allocate(dim);
      //_destination.unlock();
    //}
  }
  

  public void copyData(double data[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.copyData(data);
      //_destination.unlock();
    //}
  }
  

  public void getData(long handle[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getData(handle);
      //_destination.unlock();
    //}
  }
  
  

}
 


