#ifndef EXAMPLES_HEAT_GAUSSEIDELABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_HEAT_GAUSSEIDELABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/heat/Solver.h"

namespace examples { 
namespace heat { 
  
     class GausSeidelAbstractImplementation;
} 
}



class examples::heat::GausSeidelAbstractImplementation : public examples::heat::Solver{
     protected:
          
     public:
       GausSeidelAbstractImplementation();
       virtual ~GausSeidelAbstractImplementation();
};     


#endif
