#ifndef EXAMPLES_HEAT_INTEGRATOR_H_
#define EXAMPLES_HEAT_INTEGRATOR_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace examples { 
namespace heat { 
  
     class Integrator;
} 
}

class examples::heat::Integrator {
  public:
    virtual ~Integrator(){}
     virtual void step(const int* dims, const int dims_len,const double dt,const double* rhs, const int rhs_len,const double* stencil, const int stencil_len,const void* dof)=0;


};

#endif
