//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class IntegratorPlainJavaPort extends IntegratorAbstractPort {

  public IntegratorPlainJavaPort() {
    super();
  }
  

  public void step(final int dims[],final double dt,final double rhs[],final double stencil[],final long dof) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.step(dims,dt,rhs,stencil,dof);
      //_destination.unlock();
    //}
  }
  
  

}
 


