//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class IntegratorSocket2JavaPlainPort extends IntegratorAbstractSocketPort 
     implements java.lang.Runnable,java.nio.channels.CompletionHandler< java.nio.channels.AsynchronousSocketChannel, Object>{

  interface IntegratorSocketInvoker {
    void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  } 
  private long _ref;
  private IntegratorSocketInvoker[] _invokers;
  private java.util.concurrent.ExecutorService _executor;
  public IntegratorSocket2JavaPlainPort(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(host,port);
    _invokers = new  IntegratorSocketInvoker[214];
    	_invokers[15]= new IntegratorSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_step();
		}
	};

  }
  
  public IntegratorSocket2JavaPlainPort() throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super();
    _invokers = new  IntegratorSocketInvoker[214];
    	_invokers[15]= new IntegratorSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_step();
		}
	};

  }
  
  @Override
  public void completed(java.nio.channels.AsynchronousSocketChannel result, java.lang.Object attachment) {
    super.completed(result,attachment);
    //createInstance();
    _executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    _executor.execute(this);           
   
  }

  @Override
  public void failed(java.lang.Throwable exc, java.lang.Object attachment) {
     // TODO Auto-generated method stub
     
  }
  
  public void createInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=0;
     sendIntData(methodId);
     _ref=readLongData();
    
  }
  public void destroyInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=1;
     sendIntData(methodId);
     sendLongData(_ref);
          
  }
  
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  //public void disconnect(Integrator  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     //destroyInstance();
  //   super.disconnect(port);
  //}
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }
  
  public void close(){
     if(_executor!=null&&!_executor.isShutdown())
          _executor.shutdownNow();
     super.close();
  }
  public void run(){
     int methodId=0;
     try{
          methodId=readIntData(); 
          while(methodId!=-1){
             
              _invokers[methodId].invoke();
              methodId=readIntData();      
          }
         
     }catch(Exception e){
          
          
          de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().showError(
            IntegratorSocket2JavaPlainPort.class.getCanonicalName(),
            "run()",
            "Operation fetching error:"+e.getMessage()
           
          );
     }
     super.close();
  }

  public void invoke_step() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int dims_len=readIntData();
int []dims=new int[dims_len];
readIntData(dims,dims_len);
double dt=readDoubleData();
int rhs_len=readIntData();
double []rhs=new double[rhs_len];
readDoubleData(rhs,rhs_len);
int stencil_len=readIntData();
double []stencil=new double[stencil_len];
readDoubleData(stencil,stencil_len);
long dof=readLongData();

     step(dims,dt,rhs,stencil,dof);
     
  }
  public void step(final int dims[],final double dt,final double rhs[],final double stencil[],final long dof) {
     _destination.step(dims,dt,rhs,stencil,dof);
  }
  


}
 


