//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class IntegratorNative2JavaPlainPort extends IntegratorAbstractPort {

  private long _ref;
  public IntegratorNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Integrator  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);    
  }
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void step(final int dims[],final double dt,final double rhs[],final double stencil[],final long dof) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.step(dims,dt,rhs,stencil,dof);
      //_destination.unlock();
    //}
  }
  


}
 


