#ifndef EXAMPLES_HEAT_JACOBIABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_HEAT_JACOBIABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/heat/Solver.h"

namespace examples { 
namespace heat { 
  
     class JacobiAbstractImplementation;
} 
}



class examples::heat::JacobiAbstractImplementation : public examples::heat::Solver{
     protected:
          
     public:
       JacobiAbstractImplementation();
       virtual ~JacobiAbstractImplementation();
};     


#endif
