//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public interface Jacobi extends examples.heat.Solver,de.tum.ascodt.repository.entities.NativeComponent {

  public static final String Implementation = "examples.heat.JacobiJavaImplementation";
  

}
 


