//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public abstract class MeshAbstractJavaNativeImplementation implements Mesh {
  /**
   * Semaphore object.
   */
  private boolean  _isLocked;
  
  private String   _instanceName;
  
  protected long     _ref;
  public void setProjectLocation(String location){
  }

  public MeshAbstractJavaNativeImplementation(String instanceName) {
    assert(instanceName!=null); 
    _instanceName = instanceName;
    _isLocked     = false;
   
    System.load("/work_fast/atanasoa/Programme/runtime-HelloSocketFortran/MethodsInvocations/native/libMesh.so");
    createInstance();
  }
  public long getNativeReference(){
     return _ref;
  }
  
  /**
   * proxy for the native factory method
   */  
  public native  void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native  void destroyInstance(long ref);
 
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void lock() {
    
  }

 
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void unlock() {
   
  }
  

  
    
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public de.tum.ascodt.repository.Target getTarget() {
    return de.tum.ascodt.repository.Target.createCxxNativeTarget();
  }
  
  public de.tum.ascodt.repository.TargetParameters getTargetParameters(){
    return null;
  }

  /**
   * @see de.tum.ascodt.repository.entities
   */
  public String getInstanceName() {
    return _instanceName;
  }
  
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void setInstanceName(String instanceName){
     _instanceName=instanceName;
  }
  
  /**
   * @see de.tum.ascodt.repository.entities
   */
  public void destroy(){
     destroyInstance(_ref);
  }
  
  public long getReference(){
    return _ref;
  }
  
  public void setReference(long ref) {
     _ref=ref;
  }

  public void allocate(final int dim[]){
     
     allocate(_ref,dim);
     
  }
  public native void allocate(long ref,final int dim[]);
  

  public void copyData(double data[]){
     
     copyData(_ref,data);
     
  }
  public native void copyData(long ref,double data[]);
  

  public void getData(long handle[]){
     
     getData(_ref,handle);
     
  }
  public native void getData(long ref,long handle[]);
  

}
 


