//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class Plotter2DPlainJavaPort extends Plotter2DAbstractPort {

  public Plotter2DPlainJavaPort() {
    super();
  }
  

  public void plotPoint(final String name,final double x,final double y) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.plotPoint(name,x,y);
      //_destination.unlock();
    //}
  }
  
  

}
 


