//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class RegularGridSocket2JavaPlainPort extends RegularGridAbstractSocketPort 
     implements java.lang.Runnable,java.nio.channels.CompletionHandler< java.nio.channels.AsynchronousSocketChannel, Object>{

  interface RegularGridSocketInvoker {
    void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  } 
  private long _ref;
  private RegularGridSocketInvoker[] _invokers;
  private java.util.concurrent.ExecutorService _executor;
  public RegularGridSocket2JavaPlainPort(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(host,port);
    _invokers = new  RegularGridSocketInvoker[226];
    	_invokers[23]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setOffset();
		}
	};
	_invokers[24]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setDomain();
		}
	};
	_invokers[25]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setDimensions();
		}
	};
	_invokers[26]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_addCellScalars();
		}
	};
	_invokers[27]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_render();
		}
	};

  }
  
  public RegularGridSocket2JavaPlainPort() throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super();
    _invokers = new  RegularGridSocketInvoker[226];
    	_invokers[23]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setOffset();
		}
	};
	_invokers[24]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setDomain();
		}
	};
	_invokers[25]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setDimensions();
		}
	};
	_invokers[26]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_addCellScalars();
		}
	};
	_invokers[27]= new RegularGridSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_render();
		}
	};

  }
  
  @Override
  public void completed(java.nio.channels.AsynchronousSocketChannel result, java.lang.Object attachment) {
    super.completed(result,attachment);
    //createInstance();
    _executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    _executor.execute(this);           
   
  }

  @Override
  public void failed(java.lang.Throwable exc, java.lang.Object attachment) {
     // TODO Auto-generated method stub
     
  }
  
  public void createInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=0;
     sendIntData(methodId);
     _ref=readLongData();
    
  }
  public void destroyInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=1;
     sendIntData(methodId);
     sendLongData(_ref);
          
  }
  
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  //public void disconnect(RegularGrid  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     //destroyInstance();
  //   super.disconnect(port);
  //}
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }
  
  public void close(){
     if(_executor!=null&&!_executor.isShutdown())
          _executor.shutdownNow();
     super.close();
  }
  public void run(){
     int methodId=0;
     try{
          methodId=readIntData(); 
          while(methodId!=-1){
             
              _invokers[methodId].invoke();
              methodId=readIntData();      
          }
         
     }catch(Exception e){
          
          
          de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().showError(
            RegularGridSocket2JavaPlainPort.class.getCanonicalName(),
            "run()",
            "Operation fetching error:"+e.getMessage()
           
          );
     }
     super.close();
  }

  public void invoke_render() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     
     render();
     
  }
  public void render() {
     _destination.render();
  }
  

  public void invoke_addCellScalars() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     String variableName=readStringData();
int scalars_len=readIntData();
double []scalars=new double[scalars_len];
readDoubleData(scalars,scalars_len);

     addCellScalars(variableName,scalars);
     
  }
  public void addCellScalars(final String variableName,final double scalars[]) {
     _destination.addCellScalars(variableName,scalars);
  }
  

  public void invoke_setDimensions() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int dimensions_len=readIntData();
int []dimensions=new int[dimensions_len];
readIntData(dimensions,dimensions_len);

     setDimensions(dimensions);
     
  }
  public void setDimensions(final int dimensions[]) {
     _destination.setDimensions(dimensions);
  }
  

  public void invoke_setDomain() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int domain_len=readIntData();
double []domain=new double[domain_len];
readDoubleData(domain,domain_len);

     setDomain(domain);
     
  }
  public void setDomain(final double domain[]) {
     _destination.setDomain(domain);
  }
  

  public void invoke_setOffset() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int offset_len=readIntData();
double []offset=new double[offset_len];
readDoubleData(offset,offset_len);

     setOffset(offset);
     
  }
  public void setOffset(final double offset[]) {
     _destination.setOffset(offset);
  }
  


}
 


