//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class RegularGridNative2JavaPlainPort extends RegularGridAbstractPort {

  private long _ref;
  public RegularGridNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(RegularGrid  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);    
  }
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void setOffset(final double offset[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setOffset(offset);
      //_destination.unlock();
    //}
  }
  

  public void setDomain(final double domain[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setDomain(domain);
      //_destination.unlock();
    //}
  }
  

  public void setDimensions(final int dimensions[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setDimensions(dimensions);
      //_destination.unlock();
    //}
  }
  

  public void addCellScalars(final String variableName,final double scalars[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.addCellScalars(variableName,scalars);
      //_destination.unlock();
    //}
  }
  

  public void render() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.render();
      //_destination.unlock();
    //}
  }
  


}
 


