//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class RegularGridPlainJavaPort extends RegularGridAbstractPort {

  public RegularGridPlainJavaPort() {
    super();
  }
  

  public void setOffset(final double offset[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setOffset(offset);
      //_destination.unlock();
    //}
  }
  

  public void setDomain(final double domain[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setDomain(domain);
      //_destination.unlock();
    //}
  }
  

  public void setDimensions(final int dimensions[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setDimensions(dimensions);
      //_destination.unlock();
    //}
  }
  

  public void addCellScalars(final String variableName,final double scalars[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.addCellScalars(variableName,scalars);
      //_destination.unlock();
    //}
  }
  

  public void render() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.render();
      //_destination.unlock();
    //}
  }
  
  

}
 


