//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class SolverSocket2JavaPlainPort extends SolverAbstractSocketPort 
     implements java.lang.Runnable,java.nio.channels.CompletionHandler< java.nio.channels.AsynchronousSocketChannel, Object>{

  interface SolverSocketInvoker {
    void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  } 
  private long _ref;
  private SolverSocketInvoker[] _invokers;
  private java.util.concurrent.ExecutorService _executor;
  public SolverSocket2JavaPlainPort(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(host,port);
    _invokers = new  SolverSocketInvoker[231];
    	_invokers[31]= new SolverSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setup();
		}
	};
	_invokers[32]= new SolverSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_solve();
		}
	};

  }
  
  public SolverSocket2JavaPlainPort() throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super();
    _invokers = new  SolverSocketInvoker[231];
    	_invokers[31]= new SolverSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_setup();
		}
	};
	_invokers[32]= new SolverSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_solve();
		}
	};

  }
  
  @Override
  public void completed(java.nio.channels.AsynchronousSocketChannel result, java.lang.Object attachment) {
    super.completed(result,attachment);
    //createInstance();
    _executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    _executor.execute(this);           
   
  }

  @Override
  public void failed(java.lang.Throwable exc, java.lang.Object attachment) {
     // TODO Auto-generated method stub
     
  }
  
  public void createInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=0;
     sendIntData(methodId);
     _ref=readLongData();
    
  }
  public void destroyInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=1;
     sendIntData(methodId);
     sendLongData(_ref);
          
  }
  
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  //public void disconnect(Solver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     //destroyInstance();
  //   super.disconnect(port);
  //}
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }
  
  public void close(){
     if(_executor!=null&&!_executor.isShutdown())
          _executor.shutdownNow();
     super.close();
  }
  public void run(){
     int methodId=0;
     try{
          methodId=readIntData(); 
          while(methodId!=-1){
             
              _invokers[methodId].invoke();
              methodId=readIntData();      
          }
         
     }catch(Exception e){
          
          
          de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().showError(
            SolverSocket2JavaPlainPort.class.getCanonicalName(),
            "run()",
            "Operation fetching error:"+e.getMessage()
           
          );
     }
     super.close();
  }

  public void invoke_solve() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int dims_len=readIntData();
int []dims=new int[dims_len];
readIntData(dims,dims_len);
int stencil_len=readIntData();
double []stencil=new double[stencil_len];
readDoubleData(stencil,stencil_len);
int rhs_len=readIntData();
double []rhs=new double[rhs_len];
readDoubleData(rhs,rhs_len);
long dof_handle=readLongData();

     solve(dims,stencil,rhs,dof_handle);
     
  }
  public void solve(final int dims[],final double stencil[],final double rhs[],final long dof_handle) {
     _destination.solve(dims,stencil,rhs,dof_handle);
  }
  

  public void invoke_setup() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     double precision=readDoubleData();
int iterations=readIntData();

     setup(precision,iterations);
     
  }
  public void setup(final double precision,final int iterations) {
     _destination.setup(precision,iterations);
  }
  


}
 


