//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class SolverPlainJavaPort extends SolverAbstractPort {

  public SolverPlainJavaPort() {
    super();
  }
  

  public void setup(final double precision,final int iterations) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setup(precision,iterations);
      //_destination.unlock();
    //}
  }
  

  public void solve(final int dims[],final double stencil[],final double rhs[],final long dof_handle) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.solve(dims,stencil,rhs,dof_handle);
      //_destination.unlock();
    //}
  }
  
  

}
 


