//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class SolverNative2JavaPlainPort extends SolverAbstractPort {

  private long _ref;
  public SolverNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Solver  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);    
  }
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void setup(final double precision,final int iterations) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.setup(precision,iterations);
      //_destination.unlock();
    //}
  }
  

  public void solve(final int dims[],final double stencil[],final double rhs[],final long dof_handle) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.solve(dims,stencil,rhs,dof_handle);
      //_destination.unlock();
    //}
  }
  


}
 


