//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public interface Solver  {
  class IntegerWrapper {
    public int value;
  }
  class DoubleWrapper {
    public double value;
  }
  class StringWrapper {
    public String value;
  }
  class BooleanWrapper {
    public boolean value;
  }
  public long getReference();
  public void setReference(long ref);
  //void lock();
 
  //void unlock();
  

  public void setup(final double precision,final int iterations);

  public void solve(final int dims[],final double stencil[],final double rhs[],final long dof_handle);


}
 


