#ifndef EXAMPLES_HEAT_SORABSTRACTIMPLEMENTATION_H_
#define EXAMPLES_HEAT_SORABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "examples/heat/Solver.h"

namespace examples { 
namespace heat { 
  
     class SORAbstractImplementation;
} 
}



class examples::heat::SORAbstractImplementation : public examples::heat::Solver{
     protected:
          
     public:
       SORAbstractImplementation();
       virtual ~SORAbstractImplementation();
};     


#endif
