//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public class StencilPlainJavaPort extends StencilAbstractPort {

  public StencilPlainJavaPort() {
    super();
  }
  

  public void getStencil(double stencil[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getStencil(stencil);
      //_destination.unlock();
    //}
  }
  
  

}
 


