//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package examples.heat;


public interface Visualiser extends examples.heat.RegularGrid,de.tum.ascodt.repository.entities.Component {

  public static final String Implementation = "examples.heat.VisualiserJavaImplementation";
  

}
 


