SET(CPP_FILES
     ../../components/c++/cca/cfd/CouplingDriverAbstractImplementation.cpp
     ../../src/cca/cfd/CouplingDriverImplementation.cpp
     ../../components/c++/cca/cfd/CouplingDriverC2CxxProxy.cpp 
     ../../components/c++/tinyxml_ascodt.cpp
)

set(CPP_FILES
   	${CPP_FILES}
   	../../components/c++/cca/cfd/LBSolverNative2JavaPlainPort.cpp 
   	../../components/c++/cca/cfd/LBSolverNative2NativePlainPort.cpp
	../../components/c++/cca/cfd/LBSolverCxx2SocketPlainPort.cpp
	../../components/c++/cca/cfd/LBSolverC2CxxSocketPlainPort.cpp 
	../../components/c++/cca/cfd/LBSolverNativeDispatcher.cpp
	../../components/c++/cca/cfd/LBSolverNativeSocketDispatcher.cpp
	../../components/c++/cca/cfd/LBSolverCProxyNativeSocketDispatcher.cpp
)
set(CPP_FILES
   	${CPP_FILES}
   	../../components/c++/cca/cfd/LB2NSNative2JavaPlainPort.cpp 
   	../../components/c++/cca/cfd/LB2NSNative2NativePlainPort.cpp
	../../components/c++/cca/cfd/LB2NSCxx2SocketPlainPort.cpp
	../../components/c++/cca/cfd/LB2NSC2CxxSocketPlainPort.cpp 
	../../components/c++/cca/cfd/LB2NSNativeDispatcher.cpp
	../../components/c++/cca/cfd/LB2NSNativeSocketDispatcher.cpp
	../../components/c++/cca/cfd/LB2NSCProxyNativeSocketDispatcher.cpp
)
set(CPP_FILES
   	${CPP_FILES}
   	../../components/c++/cca/cfd/NS2LBNative2JavaPlainPort.cpp 
   	../../components/c++/cca/cfd/NS2LBNative2NativePlainPort.cpp
	../../components/c++/cca/cfd/NS2LBCxx2SocketPlainPort.cpp
	../../components/c++/cca/cfd/NS2LBC2CxxSocketPlainPort.cpp 
	../../components/c++/cca/cfd/NS2LBNativeDispatcher.cpp
	../../components/c++/cca/cfd/NS2LBNativeSocketDispatcher.cpp
	../../components/c++/cca/cfd/NS2LBCProxyNativeSocketDispatcher.cpp
)
set(CPP_FILES
   	${CPP_FILES}
   	../../components/c++/cca/cfd/NSSolverNative2JavaPlainPort.cpp 
   	../../components/c++/cca/cfd/NSSolverNative2NativePlainPort.cpp
	../../components/c++/cca/cfd/NSSolverCxx2SocketPlainPort.cpp
	../../components/c++/cca/cfd/NSSolverC2CxxSocketPlainPort.cpp 
	../../components/c++/cca/cfd/NSSolverNativeDispatcher.cpp
	../../components/c++/cca/cfd/NSSolverNativeSocketDispatcher.cpp
	../../components/c++/cca/cfd/NSSolverCProxyNativeSocketDispatcher.cpp
)
