export CCA_CFD_UEKERMANNDRIVER_JAVA=off
export CCA_CFD_UEKERMANNDRIVER_WORKERS=10
export CCA_CFD_UEKERMANNDRIVER_XML=StandaloneWorkbench.xml
export CCA_CFD_UEKERMANNDRIVER_BUFFER_SIZE=4096
../bin/cca.cfd.UekermannDriver /work_fast/atanasoa/Programme/workspace_new/LB_NS_EOF/trunk/src/configurationFiles/conf_channel_cpl.xml
