#ifndef CCA_CFD_COUPLINGDRIVERIMPLEMENTATION_H_
#define CCA_CFD_COUPLINGDRIVERIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "cca/cfd/CouplingDriverAbstractImplementation.h"
#include <string>
#include "examples/kernel/Parameters.h"
#include "examples/kernel/Configuration.h"
namespace cca { 
namespace cfd { 

class CouplingDriverImplementation;
} 
}

class cca::cfd::CouplingDriverImplementation : public cca::cfd::CouplingDriverAbstractImplementation{
	Configuration* _configuration;
	Parameters _parameters;
	double computePhysicalLBTimeStep();
	void exchangeBoundaries();
public:
	CouplingDriverImplementation();
	~CouplingDriverImplementation();
	void go(const std::string configFile);
};     


#endif
