//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package test;


public interface MyComponent extends de.tum.ascodt.repository.entities.NativeComponent {

  public static final String Implementation = "test.MyComponentJavaImplementation";
  

}
 


