//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class DriverPlainJavaPort extends DriverAbstractPort {

  public DriverPlainJavaPort() {
    super();
  }
  

  public void go() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.go();
      //_destination.unlock();
    //}
  }
  
  

}
 


