#ifndef DE_TUM_DRIVER2NATIVE2JAVAPLAINPORT_H_
#define DE_TUM_DRIVER2NATIVE2JAVAPLAINPORT_H_ 

#include "de/tum/Driver.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_de_tum_DriverNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_de_tum_DriverNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace de { 
namespace tum { 
  
     class DriverNative2JavaPlainPort;
} 
}

class de::tum::DriverNative2JavaPlainPort: public de::tum::Driver{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    DriverNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~DriverNative2JavaPlainPort();
    void go();
};
#endif
