#ifndef DE_TUM_DRIVER_H_
#define DE_TUM_DRIVER_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace de { 
namespace tum { 
  
     class Driver;
} 
}

class de::tum::Driver {
  public:
    virtual ~Driver(){}
     virtual void go()=0;


};

#endif
