/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;


import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import de.tum.ascodt.sidlcompiler.frontend.analysis.Analysis;


@SuppressWarnings("nls")
public final class AClassPackageElement extends PPackageElement {
  private TIdentifier _target_;
  private TIdentifier _name_;
  private final LinkedList<PUserDefinedType> _provides_ =
      new LinkedList<PUserDefinedType>();
  private final LinkedList<PUses> _uses_ = new LinkedList<PUses>();

  public AClassPackageElement() {
    // Constructor
  }

  public AClassPackageElement(@SuppressWarnings("hiding") TIdentifier _target_,
                              @SuppressWarnings("hiding") TIdentifier _name_,
                              @SuppressWarnings("hiding") List<PUserDefinedType> _provides_,
                              @SuppressWarnings("hiding") List<PUses> _uses_) {
    // Constructor
    setTarget(_target_);

    setName(_name_);

    setProvides(_provides_);

    setUses(_uses_);

  }

  @Override
  public void apply(Switch sw) {
    ((Analysis)sw).caseAClassPackageElement(this);
  }

  @Override
  public Object clone() {
    return new AClassPackageElement(cloneNode(_target_),
                                    cloneNode(_name_),
                                    cloneList(_provides_),
                                    cloneList(_uses_));
  }

  public TIdentifier getName() {
    return _name_;
  }

  public LinkedList<PUserDefinedType> getProvides() {
    return _provides_;
  }

  public TIdentifier getTarget() {
    return _target_;
  }

  public LinkedList<PUses> getUses() {
    return _uses_;
  }

  @Override
  void removeChild(@SuppressWarnings("unused") Node child) {
    // Remove child
    if (_target_ == child) {
      _target_ = null;
      return;
    }

    if (_name_ == child) {
      _name_ = null;
      return;
    }

    if (_provides_.remove(child)) {
      return;
    }

    if (_uses_.remove(child)) {
      return;
    }

    throw new RuntimeException("Not a child.");
  }

  @Override
  void replaceChild(@SuppressWarnings("unused") Node oldChild,
                    @SuppressWarnings("unused") Node newChild) {
    // Replace child
    if (_target_ == oldChild) {
      setTarget((TIdentifier)newChild);
      return;
    }

    if (_name_ == oldChild) {
      setName((TIdentifier)newChild);
      return;
    }

    for (ListIterator<PUserDefinedType> i = _provides_.listIterator(); i.hasNext();) {
      if (i.next() == oldChild) {
        if (newChild != null) {
          i.set((PUserDefinedType)newChild);
          newChild.parent(this);
          oldChild.parent(null);
          return;
        }

        i.remove();
        oldChild.parent(null);
        return;
      }
    }

    for (ListIterator<PUses> i = _uses_.listIterator(); i.hasNext();) {
      if (i.next() == oldChild) {
        if (newChild != null) {
          i.set((PUses)newChild);
          newChild.parent(this);
          oldChild.parent(null);
          return;
        }

        i.remove();
        oldChild.parent(null);
        return;
      }
    }

    throw new RuntimeException("Not a child.");
  }

  public void setName(TIdentifier node) {
    if (_name_ != null) {
      _name_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _name_ = node;
  }

  public void setProvides(List<PUserDefinedType> list) {
    _provides_.clear();
    _provides_.addAll(list);
    for (PUserDefinedType e : list) {
      if (e.parent() != null) {
        e.parent().removeChild(e);
      }

      e.parent(this);
    }
  }

  public void setTarget(TIdentifier node) {
    if (_target_ != null) {
      _target_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _target_ = node;
  }

  public void setUses(List<PUses> list) {
    _uses_.clear();
    _uses_.addAll(list);
    for (PUses e : list) {
      if (e.parent() != null) {
        e.parent().removeChild(e);
      }

      e.parent(this);
    }
  }

  @Override
  public String toString() {
    return "" + toString(_target_) +
           toString(_name_) +
           toString(_provides_) +
           toString(_uses_);
  }
}
