/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;


import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import de.tum.ascodt.sidlcompiler.frontend.analysis.Analysis;


@SuppressWarnings("nls")
public final class AOperation extends POperation {
  private TIdentifier _name_;
  private final LinkedList<PParameter> _parameter_ =
      new LinkedList<PParameter>();

  public AOperation() {
    // Constructor
  }

  public AOperation(@SuppressWarnings("hiding") TIdentifier _name_,
                    @SuppressWarnings("hiding") List<PParameter> _parameter_) {
    // Constructor
    setName(_name_);

    setParameter(_parameter_);

  }

  @Override
  public void apply(Switch sw) {
    ((Analysis)sw).caseAOperation(this);
  }

  @Override
  public Object clone() {
    return new AOperation(cloneNode(_name_), cloneList(_parameter_));
  }

  public TIdentifier getName() {
    return _name_;
  }

  public LinkedList<PParameter> getParameter() {
    return _parameter_;
  }

  @Override
  void removeChild(@SuppressWarnings("unused") Node child) {
    // Remove child
    if (_name_ == child) {
      _name_ = null;
      return;
    }

    if (_parameter_.remove(child)) {
      return;
    }

    throw new RuntimeException("Not a child.");
  }

  @Override
  void replaceChild(@SuppressWarnings("unused") Node oldChild,
                    @SuppressWarnings("unused") Node newChild) {
    // Replace child
    if (_name_ == oldChild) {
      setName((TIdentifier)newChild);
      return;
    }

    for (ListIterator<PParameter> i = _parameter_.listIterator(); i.hasNext();) {
      if (i.next() == oldChild) {
        if (newChild != null) {
          i.set((PParameter)newChild);
          newChild.parent(this);
          oldChild.parent(null);
          return;
        }

        i.remove();
        oldChild.parent(null);
        return;
      }
    }

    throw new RuntimeException("Not a child.");
  }

  public void setName(TIdentifier node) {
    if (_name_ != null) {
      _name_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _name_ = node;
  }

  public void setParameter(List<PParameter> list) {
    _parameter_.clear();
    _parameter_.addAll(list);
    for (PParameter e : list) {
      if (e.parent() != null) {
        e.parent().removeChild(e);
      }

      e.parent(this);
    }
  }

  @Override
  public String toString() {
    return "" + toString(_name_) + toString(_parameter_);
  }
}
