/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;


@SuppressWarnings("nls")
public abstract class Token extends Node {
  private String text;
  private int line;
  private int pos;

  public int getLine() {
    return line;
  }

  public int getPos() {
    return pos;
  }

  public String getText() {
    return text;
  }

  @Override
  void removeChild(@SuppressWarnings("unused") Node child) {
    throw new RuntimeException("Not a child.");
  }

  @Override
  void replaceChild(@SuppressWarnings("unused") Node oldChild,
                    @SuppressWarnings("unused") Node newChild) {
    throw new RuntimeException("Not a child.");
  }

  public void setLine(@SuppressWarnings("hiding") int line) {
    this.line = line;
  }

  public void setPos(@SuppressWarnings("hiding") int pos) {
    this.pos = pos;
  }

  public void setText(@SuppressWarnings("hiding") String text) {
    this.text = text;
  }

  @Override
  public String toString() {
    return text + " ";
  }
}
