/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.ascodt.sidlcompiler.frontend.node;


import de.tum.ascodt.sidlcompiler.frontend.analysis.Analysis;


@SuppressWarnings("nls")
public final class TPackageToken extends Token {
  public TPackageToken() {
    super.setText("package");
  }

  public TPackageToken(int line, int pos) {
    super.setText("package");
    setLine(line);
    setPos(pos);
  }

  @Override
  public void apply(Switch sw) {
    ((Analysis)sw).caseTPackageToken(this);
  }

  @Override
  public Object clone() {
    return new TPackageToken(getLine(), getPos());
  }

  @Override
  public void setText(@SuppressWarnings("unused") String text) {
    throw new RuntimeException("Cannot change TPackageToken text.");
  }
}
