CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/examples/heat/MeshAbstractImplementation.cpp src/examples/heat/MeshImplementation.cpp components/java/examples/heat/MeshJNIProxy.cpp 
OBJS=$(subst .cpp,.o,$(SRCS))

all: libMesh.so

libMesh.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libMesh.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libMesh.so
