CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/examples/heat/AdamsMoultonAbstractImplementation.cpp src/examples/heat/AdamsMoultonImplementation.cpp components/java/examples/heat/AdamsMoultonJNIProxy.cpp 
SRCS += components/java/examples/heat/SolverNative2JavaPlainPort.cpp components/java/examples/heat/SolverNative2NativePlainPort.cpp components/java/examples/heat/SolverNativeDispatcher.cpp
OBJS=$(subst .cpp,.o,$(SRCS))

all: libAdamsMoulton.so

libAdamsMoulton.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libAdamsMoulton.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libAdamsMoulton.so
