CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/examples/heat/JacobiAbstractImplementation.cpp src/examples/heat/JacobiImplementation.cpp components/java/examples/heat/JacobiJNIProxy.cpp 
OBJS=$(subst .cpp,.o,$(SRCS))

all: libJacobi.so

libJacobi.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libJacobi.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libJacobi.so
