CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/test/MyComponentAbstractImplementation.cpp src/test/MyComponentImplementation.cpp components/java/test/MyComponentJNIProxy.cpp 
OBJS=$(subst .cpp,.o,$(SRCS))

all: libMyComponent.so

libMyComponent.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libMyComponent.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libMyComponent.so
