#ifndef DE_TUM_DRIVERCOMPONENTIMPLEMENTATION_H_
#define DE_TUM_DRIVERCOMPONENTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "de/tum/DriverComponentAbstractImplementation.h"
#include <string>
namespace de { 
namespace tum { 
  
     class DriverComponentImplementation;
} 
}

class de::tum::DriverComponentImplementation : public de::tum::DriverComponentAbstractImplementation{
     public:
          DriverComponentImplementation();
          ~DriverComponentImplementation();
          void go();
};     


#endif
