#ifndef TEST_AIMPLEMENTATION_H_
#define TEST_AIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "test/AAbstractImplementation.h"
#include <string>
namespace test { 

     class AImplementation;
}

class test::AImplementation : public test::AAbstractImplementation{
     public:
          AImplementation();
          ~AImplementation();
          void bar();
};     


#endif
