#ifndef TEST_BIMPLEMENTATION_H_
#define TEST_BIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "test/BAbstractImplementation.h"
#include <string>
namespace test { 

     class BImplementation;
}

class test::BImplementation : public test::BAbstractImplementation{
     public:
          BImplementation();
          ~BImplementation();
          void bar();
};     


#endif
