//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package cca.cfd;


public class NS2LBSocket2JavaPlainPort extends NS2LBAbstractSocketPort 
     implements java.lang.Runnable,java.nio.channels.CompletionHandler< java.nio.channels.AsynchronousSocketChannel, Object>{

  interface NS2LBSocketInvoker {
    void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  } 
  private long _ref;
  private NS2LBSocketInvoker[] _invokers;
  private java.util.concurrent.ExecutorService _executor;
  public NS2LBSocket2JavaPlainPort(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(host,port);
    _invokers = new  NS2LBSocketInvoker[264];
    	_invokers[54]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_iterate();
		}
	};
	_invokers[55]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_iterateParallel();
		}
	};
	_invokers[56]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveTimestep();
		}
	};
	_invokers[57]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveTimestepParallel();
		}
	};
	_invokers[58]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesSize();
		}
	};
	_invokers[59]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesSizeParallel();
		}
	};
	_invokers[60]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesCopy();
		}
	};
	_invokers[61]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesCopyParallel();
		}
	};
	_invokers[62]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveJacobianCopy();
		}
	};
	_invokers[63]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveJacobianCopyParallel();
		}
	};
	_invokers[64]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrievePressureCopy();
		}
	};
	_invokers[65]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrievePressureCopyParallel();
		}
	};

  }
  
  public NS2LBSocket2JavaPlainPort() throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super();
    _invokers = new  NS2LBSocketInvoker[264];
    	_invokers[54]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_iterate();
		}
	};
	_invokers[55]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_iterateParallel();
		}
	};
	_invokers[56]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveTimestep();
		}
	};
	_invokers[57]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveTimestepParallel();
		}
	};
	_invokers[58]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesSize();
		}
	};
	_invokers[59]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesSizeParallel();
		}
	};
	_invokers[60]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesCopy();
		}
	};
	_invokers[61]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveVelocitiesCopyParallel();
		}
	};
	_invokers[62]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveJacobianCopy();
		}
	};
	_invokers[63]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrieveJacobianCopyParallel();
		}
	};
	_invokers[64]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrievePressureCopy();
		}
	};
	_invokers[65]= new NS2LBSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_retrievePressureCopyParallel();
		}
	};

  }
  
  @Override
  public void completed(java.nio.channels.AsynchronousSocketChannel result, java.lang.Object attachment) {
    super.completed(result,attachment);
    //createInstance();
    _executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    _executor.execute(this);           
   
  }

  @Override
  public void failed(java.lang.Throwable exc, java.lang.Object attachment) {
     // TODO Auto-generated method stub
     
  }
  
  public void createInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=0;
     sendIntData(methodId);
     _ref=readLongData();
    
  }
  public void destroyInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=1;
     sendIntData(methodId);
     sendLongData(_ref);
          
  }
  
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  //public void disconnect(NS2LB  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     //destroyInstance();
  //   super.disconnect(port);
  //}
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }
  
  public void close(){
     if(_executor!=null&&!_executor.isShutdown())
          _executor.shutdownNow();
     super.close();
  }
  public void run(){
     int methodId=0;
     try{
          methodId=readIntData(); 
          while(methodId!=-1){
             
              _invokers[methodId].invoke();
              methodId=readIntData();      
          }
         
     }catch(Exception e){
          de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
     }
     super.close();
  }

  public void invoke_retrievePressureCopy() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int pressure_len=readIntData();
double []pressure=new double[pressure_len];
readDoubleData(pressure,pressure_len);

     retrievePressureCopy(pressure);
     sendIntData(pressure.length);
sendDoubleData(pressure);

  }
  public void invoke_retrievePressureCopyParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void retrievePressureCopy(double pressure[]) {
     _destination.retrievePressureCopy(pressure);
  }
  public void retrievePressureCopyParallel(double pressure[]) {
     _destination.retrievePressureCopyParallel(pressure);
  }
  
  

  public void invoke_retrieveJacobianCopy() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int jacobian_len=readIntData();
double []jacobian=new double[jacobian_len];
readDoubleData(jacobian,jacobian_len);

     retrieveJacobianCopy(jacobian);
     sendIntData(jacobian.length);
sendDoubleData(jacobian);

  }
  public void invoke_retrieveJacobianCopyParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void retrieveJacobianCopy(double jacobian[]) {
     _destination.retrieveJacobianCopy(jacobian);
  }
  public void retrieveJacobianCopyParallel(double jacobian[]) {
     _destination.retrieveJacobianCopyParallel(jacobian);
  }
  
  

  public void invoke_retrieveVelocitiesCopy() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int velocityX_len=readIntData();
double []velocityX=new double[velocityX_len];
readDoubleData(velocityX,velocityX_len);
int velocityY_len=readIntData();
double []velocityY=new double[velocityY_len];
readDoubleData(velocityY,velocityY_len);
int velocityZ_len=readIntData();
double []velocityZ=new double[velocityZ_len];
readDoubleData(velocityZ,velocityZ_len);

     retrieveVelocitiesCopy(velocityX,velocityY,velocityZ);
     sendIntData(velocityX.length);
sendDoubleData(velocityX);
sendIntData(velocityY.length);
sendDoubleData(velocityY);
sendIntData(velocityZ.length);
sendDoubleData(velocityZ);

  }
  public void invoke_retrieveVelocitiesCopyParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void retrieveVelocitiesCopy(double velocityX[],double velocityY[],double velocityZ[]) {
     _destination.retrieveVelocitiesCopy(velocityX,velocityY,velocityZ);
  }
  public void retrieveVelocitiesCopyParallel(double velocityX[],double velocityY[],double velocityZ[]) {
     _destination.retrieveVelocitiesCopyParallel(velocityX,velocityY,velocityZ);
  }
  
  

  public void invoke_retrieveVelocitiesSize() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int [] memory= new int[1];
readIntData(memory,1);

     retrieveVelocitiesSize(memory);
     sendIntData(memory);

  }
  public void invoke_retrieveVelocitiesSizeParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void retrieveVelocitiesSize(int memory[]) {
     _destination.retrieveVelocitiesSize(memory);
  }
  public void retrieveVelocitiesSizeParallel(int memory[]) {
     _destination.retrieveVelocitiesSizeParallel(memory);
  }
  
  

  public void invoke_retrieveTimestep() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     double [] timestep= new double[1];
readDoubleData(timestep,1);

     retrieveTimestep(timestep);
     sendDoubleData(timestep);

  }
  public void invoke_retrieveTimestepParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void retrieveTimestep(double timestep[]) {
     _destination.retrieveTimestep(timestep);
  }
  public void retrieveTimestepParallel(double timestep[]) {
     _destination.retrieveTimestepParallel(timestep);
  }
  
  

  public void invoke_iterate() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     
     iterate();
     
  }
  public void invoke_iterateParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void iterate() {
     _destination.iterate();
  }
  public void iterateParallel() {
     _destination.iterateParallel();
  }
  
  


}
 


